name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: install newlib
      run: sudo apt install kos-newlib

    - name: Build
      run: make TermBoard

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: TermBoard
